Actually remove ospec from the main code base
MithrilJS/mithril.js pull request #2786
Opened 2022-06-10 16:22 UTC by pygy

It is still used as a `dev-dependency`.

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation change

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated `docs/changelog.md`

2022-06-10 16:26 UTC, barneycarroll requested changes

2022-06-10 16:26 UTC, barneycarroll commented on docs/contributing.md
> +After having run `npm install` (a one-time operation), ou can run `npm run test` from the command line to run all tests.
```suggestion
After having run `npm install` (a one-time operation), run `npm run test` from the command line to run all tests.
```

2022-06-10 16:29 UTC, barneycarroll approved these changes

2022-06-10 16:33 UTC, merged

2022-06-11 12:03 UTC, dead-claudia commented
> Uh oh... we should have tagged this I guess for pr-release to mark it as breaking. Or maybe not, since ospec deprecation was announced for v2.2... Dunno

It's breaking, hence why I held it back.

Also, I'm super glad I asked what would happen if we forgot to tag something...