Fix tiny bugs of setAttr()/updateStyle()
MithrilJS/mithril.js pull request #2988
Opened 2024-11-08 10:47 UTC by kfule

Fixed a few bugs in attributes and style properties updates that almost never happen.

## Description

- removes `key === "is"` from `setAttr()` to fix 2799 https://github.com/MithrilJS/mithril.js/issues/2799#issuecomment-2464260940
- swaps set and removal order in updateAttrs()/updateStyle() to prevent accidental removal for newly setting values

## Motivation and Context

I found a strange behavior in the process of #2985, although it rarely happens (https://github.com/MithrilJS/mithril.js/pull/2985#issuecomment-2459950783). And there seems to be a similar trivial issue in `updateAttrs()` ([flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AOmgD0kgAQATDMQwBaAFTqZEODIByAeQAqM6hjgxlZtHAjEIANxgTpMuMQCesGQAcATrS8wPrbwMoQYDjLEAO60xqYhABQmOFAAwvEyGGhy8qaEyiZmAJQSdhg+mTIAvDJYCWIgcvYNFDLADQpKFthesACScg2IMg1gtLQtLu6ww8AARhjUANYA5n4ArtmptFC0PsMNPjCDbOwj4OMNJWhlFXPVtfWNzZRtHYoqcD2wECcHIAsfJNXB4YLMGgtlmtaJs5AUdnshuc5lB1o5Tq1RpcQNcnLJIasNtljAiKloZEdBmgsPgjtlAgk5LRqOscAx8HNaHI3K0MLipPjFoSYcS6Lsydo0LRiDIUWiKAqJDS6XIGUyWWziByuTzZfznJ1Pt8YL9NJLpcjyg18DaJEI4DsYPhditGczWSJ8ABHNE+NwAZRgsGoxD2Tyadiu+BWMGIAEFiMQfBA5utGOGPt0sL0TScitdKCAzMHbPQEDwAIwAJkQAGYq2wOCBMDg8PhqHABDR6IxmDw2ABdKhQCBoJbl1DNrh4LA2QjJqAAASr+AADPgACyF9Y+cg8EjELxwRDSTZeVbt2hYSSz4jz6DLtebm9zhf4WdofD8QvuAJ4ODUMmXiiFQxYwCGEBlngq6IKuygwVWADs9YAJyDqwQA).)
This could be solved by simply swapping the order of set and removal probably without creating new bugs and perf issues.

Also, I am not very familiar with custom elements, but it seemed to me that the #2799 issue could be solved by simply removing `key === "is"` from `setAttr()`.

## How Has This Been Tested?

- `npm run test` including test code fix for custom elements
  - Sorry, but I did not make any changes to domMock because the changes seemed more complicated than the bug fix code.
- I have also confirmed that the issues are not reproduced in flems above using fixed bundle.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] My change requires a documentation update, and I've opened a pull request to update it already:
- [x] I have read https://mithril.js.org/contributing.html.

2024-11-08 10:57 UTC, kfule commented
I am a little sorry for my frequent pull requests these days.😢
I did not plan for this pull request, but it seemed like an easy bug to fix...

2024-11-08 13:29 UTC, dead-claudia requested changes
You still need to fix the diff algorithm (this will have negative perf impact) to compare `is` values for non-custom element vnodes.

- If the `is` attribute disappears, the element needs replaced so it's no longer a custom element.
- If the `is` attribute is newly added, the element needs replaced so it's now a custom element.
- If the `is` attribute changes, the backing custom element needs to change to be that new type.

In all three cases, it's simpler and more predictable to just remove and re-create.

2024-11-08 14:44 UTC, kfule commented
@dead-claudia 
Thanks for the comment. As you commented, this PR is going to have unpredictable behavior for users (even if it is straightforward javascript behavior). I will take some time to think about it some more.

I think I will close this PR for now. There is no hurry at all to fix the other bugs in this PR.

2024-11-08 18:51 UTC, dead-claudia commented
> @dead-claudia 
> 
> Thanks for the comment. As you commented, this PR is going to have unpredictable behavior for users (even if it is straightforward javascript behavior). I will take some time to think about it some more.
> 
> I think I will close this PR for now. There is no hurry at all to fix the other bugs in this PR.

@kfule The current behavior isn't any more "predictable". What I suggested was really just a one line fix plus some more (pretty straightforward) tests. Sorry if this wasn't clear.

2025-02-04 12:02 UTC, kfule commented
@dead-claudia 
I have reopened this PR. I would like to request your review.

The following changes related to attr/style have been added to the previous PR. Both are small changes, I think.
- remove `key === "is"` from removeAttr() as well (mainly for code consistency with setAttr())
- remove cssText property access (cf. #2811)

I have not added any tests, but I would like to add tests if needed.

----
Also, I thought about your comment about "is" being "unpredictable".
When the value of "is" is set/changed/deleted, it would be better to delete the element and re-create it as you commented.
For instance, it would look fine to change [the call updateElement()](https://github.com/MithrilJS/mithril.js/blob/v2.2.13/render/render.js#L411) as follows:

```
default: {
	if ((old.attrs && old.attrs.is) == (vnode.attrs && vnode.attrs.is)) {
		updateElement(old, vnode, hooks, ns)
	} else {
		removeNode(parent, old)
		createElement(parent, vnode, hooks, ns, nextSibling)
	}
}
```
However, I personally would be more careful about adding code to this area because of the performance impact (about a several percent drop).
The "is" attribute has not yet been implemented in safari and does not seem to be planned to be implemented. I don't think I will be using “is” for a while yet.

2025-02-04 20:51 UTC, dead-claudia commented
> @dead-claudia 
> 
> I have reopened this PR. I would like to request your review.
> 
> 
> 
> The following changes related to attr/style have been added to the previous PR. Both are small changes, I think.
> 
> - remove `key === "is"` from removeAttr() as well (mainly for code consistency with setAttr())
> 
> - remove cssText property access (cf. #2811)
> 
> 
> 
> I have not added any tests, but I would like to add tests if needed.
> 
> 
> 
> ----
> 
> Also, I thought about your comment about "is" being "unpredictable".
> 
> When the value of "is" is set/changed/deleted, it would be better to delete the element and re-create it as you commented.
> 
> For instance, it would look fine to change [the call updateElement()](https://github.com/MithrilJS/mithril.js/blob/v2.2.13/render/render.js#L411) as follows:
> 
> 
> 
> ```
> 
> default: {
> 
> 	if ((old.attrs && old.attrs.is) == (vnode.attrs && vnode.attrs.is)) {
> 
> 		updateElement(old, vnode, hooks, ns)
> 
> 	} else {
> 
> 		removeNode(parent, old)
> 
> 		createElement(parent, vnode, hooks, ns, nextSibling)
> 
> 	}
> 
> }
> 
> ```
> 
> However, I personally would be more careful about adding code to this area because of the performance impact (about a several percent drop).

Try adding a `bits` field to the vnode that has the lowest bit set (`var IS_CUSTOMIED_BUILTIN = 1 << 0`) if it's a customized built-in. There's slight memory tradeoff (10 -> 11 fields, or 52 -> 56 bytes in V8), but it won't impact much else. Be sure to add it as the first field so it's most likely to reside on the same cache page as the tag.

A bit test from a field allocated inline in the object is very cheap. It's only a few bottlenecking instructions (4-6 at most) in the fast path plus an extra immediate generation + memory store (that won't bottleneck), so it should avoid significant perf deviations.

2025-02-05 11:57 UTC, kfule commented
@dead-claudia 
Thank you for your comment including great insight!
I think a 1-bit flag can not evaluate the change of `is` (e.g. `"foo"` -> `"bar"`). However, I found that adding an additional `is` field to the vnode itself (like `vnode.key`) and setting it in m(), as you suggested, keeps the performance almost the same as in v2.2.13.

So, I have added code and tests to this PR to recreate the node if the `is` is changed. I think “unpredictable” has been improved by this PR.

2025-02-05 16:16 UTC, kfule commented
> For instance, it would look fine to change [the call updateElement()](https://github.com/MithrilJS/mithril.js/blob/v2.2.13/render/render.js#L411) as follows:

Before "the call updateElement()", there was already a process that assumed an update.
https://github.com/MithrilJS/mithril.js/blob/v2.2.13/render/render.js#L400-L402
https://github.com/MithrilJS/mithril.js/blob/v2.2.13/render/render.js#L405

Therefore, it is needed to evaluate `is` before those processes, and it is safer to evaluate it at the beginning as well as `tag` after all.

2025-02-05 23:42 UTC, dead-claudia commented
> @dead-claudia 
> 
> Thank you for your comment including great insight!
> 
> I think a 1-bit flag can not evaluate the change of `is` (e.g. `"foo"` -> `"bar"`). However, I found that adding an additional `is` field to the vnode itself (like `vnode.key`) and setting it in `m()`, as you suggested, keeps the performance almost the same as in v2.2.13.

The idea wasn't to replace the field access, but to not pay the cost of checking it unless it's actually there.

Hope this helps.

2025-02-05 23:48 UTC, dead-claudia requested changes

2025-02-05 23:48 UTC, dead-claudia commented on render/hyperscript.js
> +	return Object.keys(object).length === 0
Did you confirm this to be necessary while benchmarking?

What's the tradeoff here? I didn't see anything in the commit message clarifying why it's necessary.

If it's not actually boosting anything, please revert it. It was originally made to use `for ... in` for perf reasons, so I don't want that to change unless it needs to.

2025-02-06 03:44 UTC, kfule commented on render/hyperscript.js
> +	return Object.keys(object).length === 0
OK, I'll revert back to the previous code.
The purpose of this change was to reduce the amount of code rather than for performance purposes.
I should have detailed the purpose as it is not directly related to this PR.

2025-02-06 03:55 UTC, kfule commented
@dead-claudia 
Sorry, I misunderstood the use of flag you suggested... :sweat_smile:
However, if there are no problems, I will leave the current dedicated field `is` as it is. Since the current code has a better look and feel.
I will revert isEmpty() and request the review again.

2025-02-06 13:23 UTC, kfule commented
Sorry, I found `vnode.attrs.is` and changed it to use `vnode.is`.
If there are no additional comments, I would like to make this the last commit for this PR.

2025-02-08 01:00 UTC, dead-claudia requested changes
Sorry, didn't do a detailed review the first time, my apologies.

This *should* be the last of my questions and requests.

2025-02-08 04:33 UTC, kfule commented
@dead-claudia 
Thanks for the review comment!
I'll take a look at each of your comments.

2025-02-08 05:15 UTC, kfule commented on render/render.js
> -		if (key === "key" || key === "is" || old == null || isLifecycleMethod(key)) return
Is the same question [this one](https://github.com/MithrilJS/mithril.js/pull/2988#pullrequestreview-2423815558)?

With the recent commit to improve the handling of `is`, the element is removed and recreated if the `is` attribute changes.  So, setAttr/removeAttr should now look like this.
- In setAttr, the value of `vnode.attrs.is` is simply set like any other attribute when the is-element is created or recreated. This fixes #2722 (CSS issue).
- As for removeAttr, if the value of `vnode.attrs.is`(`vnode.is`) is changed or removed, updateElement is not called, so removeAttr is also not called. Therefore, the `key === "is"` in removeAttr is no longer needed.
 
Also, the evaluation of `key === "is"` is reduced when trying to set or remove other attributes.

2025-02-08 05:34 UTC, kfule commented on render/render.js
> +		// so removal should be done first to prevent accidental removal for newly setting values.
> That's what the inner `attrs[key] == null` condition is for in the remove loop.

Yes, that condition is the cause of the deletion issue.

An example of a test case that does not work well with the old mithril code is the [flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AOmgD0kgAQATDMQwBaAFTqZEODIByAeQAqM6hjgxlZtHAjEIANxgTpMuMQCesGQAcATrS8wPrbwMoQYDjLEAO60xqYhABQmOFAAwvEyGGhy8qaEyiZmAJQSdhg+mTIAvDJYCWIgcvYNFDLADQpKFthesACScg2IMg1gtLQtLu6ww8AARhjUANYA5n4ArtmptFC0PsMNPjCDbOwj4OMNJWhlFXPVtfWNzZRtHYoqcD2wECcHIAsfJNXB4YLMGgtlmtaJs5AUdnshuc5lB1o5Tq1RpcQNcnLJIasNtljAiKloZEdBmgsPgjtlAgk5LRqOscAx8HNaHI3K0MLipPjFoSYcS6Lsydo0LRiDIUWiKAqJDS6XIGUyWWziByuTzZfznJ1Pt8YL9NJLpcjyg18DaJEI4DsYPhditGczWSJ8ABHNE+NwAZRgsGoxD2Tyadiu+BWMGIAEFiMQfBA5utGOGPt0sL0TScitdKCAzMHbPQEDwAIwAJkQAGYq2wOCBMDg8PhqHABDR6IxmDw2ABdKhQCBoJbl1DNrh4LA2QjJqAAASr+AADPgACyF9Y+cg8EjELxwRDSTZeVbt2hYSSz4jz6DLtebm9zhf4WdofD8QvuAJ4ODUMmXiiFQxYwCGEBlngq6IKuygwVWADs9YAJyDqwQA) described in the description at the top of this PR.

The performance does not seem to be affected by this code swap.
As for the bundle size, the bundle size is reduced by 1 byte gzipped due to the `console.warn` move (the code `old &&` is removed).

2025-02-08 05:43 UTC, kfule commented on render/render.js
> +		// so removal should be done first to prevent accidental removal for newly setting values.
I changed only this part and measured the bundle size.

original (current main branch)
Original size: 20,075 bytes gzipped (67,460 bytes uncompressed)
Compiled size: 8,960 bytes gzipped (24,405 bytes uncompressed)

swap without console.warn move
Original size: 20,082 bytes gzipped (67,460 bytes uncompressed)
Compiled size: 8,963 bytes gzipped (24,405 bytes uncompressed)

this PR (with console.warn move)
Original size: 20,081 bytes gzipped (67,456 bytes uncompressed)
Compiled size: 8,959 bytes gzipped (24,402 bytes uncompressed)

2025-02-08 05:58 UTC, kfule commented on render/render.js
> +			// so removal should be done first to prevent accidental removal for newly setting values.
The test cases are the same [flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AOmgD0kgAQATDMQwBaAFTqZEODIByAeQAqM6hjgxlZtHAjEIANxgTpMuMQCesGQAcATrS8wPrbwMoQYDjLEAO60xqYhABQmOFAAwvEyGGhy8qaEyiZmAJQSdhg+mTIAvDJYCWIgcvYNFDLADQpKFthesACScg2IMg1gtLQtLu6ww8AARhjUANYA5n4ArtmptFC0PsMNPjCDbOwj4OMNJWhlFXPVtfWNzZRtHYoqcD2wECcHIAsfJNXB4YLMGgtlmtaJs5AUdnshuc5lB1o5Tq1RpcQNcnLJIasNtljAiKloZEdBmgsPgjtlAgk5LRqOscAx8HNaHI3K0MLipPjFoSYcS6Lsydo0LRiDIUWiKAqJDS6XIGUyWWziByuTzZfznJ1Pt8YL9NJLpcjyg18DaJEI4DsYPhditGczWSJ8ABHNE+NwAZRgsGoxD2Tyadiu+BWMGIAEFiMQfBA5utGOGPt0sL0TScitdKCAzMHbPQEDwAIwAJkQAGYq2wOCBMDg8PhqHABDR6IxmDw2ABdKhQCBoJbl1DNrh4LA2QjJqAAASr+AADPgACyF9Y+cg8EjELxwRDSTZeVbt2hYSSz4jz6DLtebm9zhf4WdofD8QvuAJ4ODUMmXiiFQxYwCGEBlngq6IKuygwVWADs9YAJyDqwQA).

The performance does not seem to be affected by this code swap, too.
The changes in bundle size are as follows.

original (current main branch)
Original size: 20,075 bytes gzipped (67,460 bytes uncompressed)
Compiled size: 8,960 bytes gzipped (24,405 bytes uncompressed)

original + swap this part (like this PR)
Original size: 20,078 bytes gzipped (67,460 bytes uncompressed)
Compiled size: 8,959 bytes gzipped (24,406 bytes uncompressed)

original + swap this part + swap updateAttrs part (like this PR)
Original size: 20,085 bytes gzipped (67,456 bytes uncompressed)
Compiled size: 8,959 bytes gzipped (24,403 bytes uncompressed)

Even with the two swaps, it looked like a 1-byte gzipped reduction in the end.

2025-02-08 12:10 UTC, kfule commented on render/hyperscript.js
> +	if (hasOwn.call(attrs, "is")) vnode.is = attrs.is
Compared to the following code, the performance degradation is indeed reduced.
(The following code evaluates both `old` and `vnode` including the null check of attrs at each rendering.)
```Javascript
function updateNode(parent, old, vnode, hooks, nextSibling, ns) {
	var oldTag = old.tag, tag = vnode.tag
	if (oldTag === tag && (old.attrs && old.attrs.is) === (vnode.attrs && vnode.attrs.is)) {
		vnode.state = old.state
		vnode.events = old.events
```
In that sense, the comment seems correct. However, the comment may be inaccurate because, as per your earlier comment, the performance of m() itself is a bit degraded.

And your comment made me realize that there are several ways to check and assign to `vnode.is`.
I benchmarked several variations and will describe the results separately.

2025-02-08 12:22 UTC, kfule commented on render/vnode.js
> +	return {tag: tag, key: key, attrs: attrs, children: children, text: text, dom: dom, is: is, domSize: undefined, state: undefined, events: undefined, instance: undefined}
Personally, I would like to keep the possibility of using Vnode() directly. This is not a strong demand at all, though.

Also, I posted a benchmark in another comment, and one of the better results was to `return Vnode("", attrs.key, attrs, children, undefined, undefined, attrs.is)` in `hyperscriptVnode()`. If this PR is to be changed to this style, it will remain here.

2025-02-08 12:32 UTC, kfule commented on render/vnode.js
> +	return {tag: tag, key: key, attrs: attrs, children: children, text: text, dom: dom, is: is, domSize: undefined, state: undefined, events: undefined, instance: undefined}
Sorry, I forgot the case where `is` is defined in the CSS selector. So it looks like set in `execSelector()` is better than set in `hyperscriptVnode()`.

2025-02-08 12:34 UTC, kfule commented
@dead-claudia 
Thank you for your review comments. I have replied to all your comments.

I have also measured the benchmark and it seems to me that for `if (hasOwn.call(attrs, "is")) vnode.is = attrs.is` it would be better to change to either of the following.
- `if (attrs.is != null) vnode.is = attrs.is` in `execSelector()`
- `return Vnode("", attrs.key, attrs, children, undefined, undefined, attrs.is)` in `hyperscriptVnode()`

Also, there is a case where `is` is defined in the CSS selector, so it looks better to set it in `execSelector()`.

2025-02-08 12:42 UTC, kfule commented on render/vnode.js
> +	return {tag: tag, key: key, attrs: attrs, children: children, text: text, dom: dom, is: is, domSize: undefined, state: undefined, events: undefined, instance: undefined}
I think I would never use `is` directly with `Vnode()`, so I just initialize it with `undefined` as per your comment.

2025-02-08 17:25 UTC, dead-claudia commented
@kfule Try `vnode.is = attrs.is` in `execSelector`, without the condition. That'd be best for performance (1 optimized lookup + 1 store), and you could then drop the extra argument to `Vnode`. Doing the set there only would also ensure that it only works for elements and not as a magic positional `key` for other stuff (which, for design reasons, I'd rather not have - such magic properties should be usable without exception, so custom element vnodes can leverage them).

2025-02-08 17:28 UTC, dead-claudia requested changes
Let me know how this impacts performance. Once this is addressed, I'm more than happy to merge.

2025-02-08 17:28 UTC, dead-claudia commented on render/hyperscript.js
> +	if (attrs.is != null) vnode.is = attrs.is
```suggestion
	vnode.is = attrs.is
```

2025-02-08 17:33 UTC, dead-claudia commented on render/render.js
> -		if (key === "key" || key === "is" || old == null || isLifecycleMethod(key)) return
Ack! Sorry, forgot to delete this comment when I deleted a comment about `setAttr`. So, please ignore. 😅

2025-02-08 17:35 UTC, dead-claudia commented on render/render.js
> +		// so removal should be done first to prevent accidental removal for newly setting values.
> An example of a test case that does not work well with the old mithril code is the flems described in the description at the top of this PR.

Could you add the test case to this PR (if you don't have similar already)?

2025-02-08 17:37 UTC, dead-claudia commented
Edit: also add https://github.com/MithrilJS/mithril.js/pull/2988#discussion_r1947913371 to the list of changes needed.

2025-02-08 18:45 UTC, kfule commented on render/hyperscript.js
> +	if (attrs.is != null) vnode.is = attrs.is
The result of `vnode.is = attrs.is` case is in the folded benchmark table in [the comment above](https://github.com/MithrilJS/mithril.js/pull/2988#issuecomment-2645286844) (`vnode.is = attrs.is in execSelector()` is it).
In this measurement, it appears to be only slightly slower than the case with the if-condition (only about 0.5%, though this may be within the margin of error).

Especially since the `npm run perf` benchmark doesn't use `is` at all, so the benchmark results may be explained by the optimization with branch prediction (I don't know much about the details of the JS engine, though...).

2025-02-08 18:53 UTC, kfule commented on render/render.js
> +		// so removal should be done first to prevent accidental removal for newly setting values.
Would a manual test case (like in #3002) be acceptable?
I think the dom mock does not emulate the special case handling of such cases.

2025-02-08 19:33 UTC, kfule commented on render/render.js
> +		// so removal should be done first to prevent accidental removal for newly setting values.
I added manual test similar to flems.

2025-02-08 19:43 UTC, kfule commented
@dead-claudia 
I have added a manual test code.

As I mentioned in my comment [above](https://github.com/MithrilJS/mithril.js/pull/2988#discussion_r1947927692), the benchmark results showed that `if (attrs.is != null) vnode.is = attrs.is` was slightly faster than `vnode.is = attrs.is`.
However, the difference is about 0.5%, so it may be within the margin of error.
I honestly don't care which code is used. Compared to the 7% drop, this is not a big problem.

2025-02-08 20:20 UTC, kfule commented
I ran the benchmark again, and it still seems to be faster with the if-condition (about 0.5%).


#### result of `vnode.is = attrs.is` (~0.5% slower?)

<details>

| |1|2|3|4|5|max|min|mid3-average|vs main|vs "if (attrs.is != null)"|
|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|
|construct large vnode tree|61128|61463|61628|60831|60923|61,628 |60,831 |61,171.33 |100.41|99.45|
|rerender identical vnode|12219128|14976356|14144199|14020772|13857496|14,976,356 |12,219,128 |14,007,489.00 |104.84|98.78|
|rerender same tree|288328|289343|284116|283618|289411|289,411 |283,618 |287,262.33 |97.92|99.51|
|add large nested tree|25748|25843|25750|25626|25674|25,843 |25,626 |25,724.00 |96.60|99.96|
|mutate styles/properties|581|603|578|596|599|603 |578 |592.00 |99.27|99.72|
|repeated add/removal|12656|11643|11700|11616|11636|12,656 |11,616 |11,659.67 |99.95|100.13|

</details>

#### result of `if (attrs.is != null) vnode.is = attrs.is`

<details>

| |1|2|3|4|5|max|min|mid3-average|vs main|vs "if (attrs.is != null)"|
|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|:----|
|construct large vnode tree|61500|61491|61837|61100|61547|61,837 |61,100 |61,512.67 |100.97|100.00|
|rerender identical vnode|14527141|13936277|14911581|13119917|14079527|14,911,581 |13,119,917 |14,180,981.67 |106.14|100.00|
|rerender same tree|288368|286976|290087|289016|288641|290,087 |286,976 |288,675.00 |98.41|100.00|
|add large nested tree|25778|25658|25351|25808|25769|25,808 |25,351 |25,735.00 |96.64|100.00|
|mutate styles/properties|594|604|579|590|597|604 |579 |593.67 |99.55|100.00|
|repeated add/removal|11704|11886|11606|11624|11581|11,886 |11,581 |11,644.67 |99.83|100.00|

</details>

2025-02-08 23:21 UTC, dead-claudia commented on render/hyperscript.js
> +	if (attrs.is != null) vnode.is = attrs.is
I apparently overestimated the gain, though it's an extremely hot piece of code called potentially millions of times per second, even on mobile: 20k elements * 60 FPS = 1.2m calls/second. As browsers need about 5ms to draw a 60 FPS frame, that leaves about 10ms of available render time, and 10k element vnodes would need to be constructed and painted in an effective rate of 1m calls/sec or 1us/call just to meet that deadline and not drop frames.

I still prefer it to save a few bytes anyways, but this should give you an idea of why perf matters so much for it.

> the benchmark results may be explained by the optimization with branch prediction

Yes, but it's not all just the CPU.

- Branch prediction typically requires a half cycle of overhead for a successfully predicted branch, for a total of two levels of prediction and speculative decoding. Past that, CPUs will not speculate, not even when the same decode line contains 3+ branches (which can happen, but is rare). On a 4 GHz desktop processor, this comes out to an effective throughput of about 0.125 ns/branch, and on a 2 GHz mobile processor, about 0.25 ns/branch.
- By not branching, engines have one less branch to trace for their JIT. There's sometimes still profiling overhead with it, in case call patterns change and the JIT needs to recompile a branch. (V8 does this because of past Node.js perf issues.) This counter requires an additional atomic increment, which may require an extra cycle or two on top of the half-cycle overhead for successful branch prediction. (In particular, AArch64 will suffer here.)
- The renderer is currently optimized enough to support up to around 100k or so elements at 60 FPS on laptop, or about 100ns per element, and 50k or so on mobile, or about 200ns per element. If you take profiles of the benchmarks (even in-browser), about 4-5% of time spent in updates is in `m`, or about 2-10ns per call on average. (The overhead of the DOM calls are negligible in small updates, so mock vs real DOM makes little difference.) A single successful branch prediction in the hot path equates to about 2-10% of total runtime of `m`, or about 0.1-0.5% of a whole render on average. If most vnodes are elements, that'll matter a *lot*, and so 0.5% is entirely reasonable to expect in some situations.

2025-02-08 23:24 UTC, dead-claudia commented on render/hyperscript.js
> +	if (attrs.is != null) vnode.is = attrs.is
Or in other words, it's small and margin-of-error in a single run, but will likely appear across multiple runs.

2025-02-08 23:27 UTC, dead-claudia approved these changes

2025-02-08 23:28 UTC, merged

2025-02-09 00:28 UTC, kfule commented on render/hyperscript.js
> +	if (attrs.is != null) vnode.is = attrs.is
Thank you very much for sharing such detailed information and valuable insights!

2025-02-09 03:40 UTC, dead-claudia commented on render/hyperscript.js
> +	if (attrs.is != null) vnode.is = attrs.is
Welcome!